name: Build and push mm-discovery-server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/mm-discovery-server:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mm-discovery-server:latest

      - name: Trigger redeploy
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mankis-movie-mate/mm-infrastructure
          event-type: discovery-server-builded
          client-payload: '{"service": "mm-discovery-server", "tag": "latest"}'
          token: ${{ secrets.MM_TOKEN }}